#!/bin/bash
export LD_LIBRARY_PATH=/opt/cray/libfabric/1.22.0/lib64:/opt/cray/pe/papi/7.2.0.1/lib64:/opt/cray/pe/papi/7.1.0.4/lib64:${LD_LIBRARY_PATH:-}
exec /pdc/software/eb/software/apptainer/1.4.4/bin/apptainer "$@"
